"""Process exit codes shared by the launcher and camera child process."""

CAMERA_CLOSED = 0
APPLICATION_EXIT_REQUESTED = 20
CONTROL_SCAN_CAMERA = 21
CONTROL_SCAN_SCREEN = 22
CONTROL_PAIR_PHONE = 23
CONTROL_EXIT_REQUESTED = 24
